# Generated by Django 2.2.3 on 2024-02-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_auto_20240219_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdata',
            name='id',
        ),
        migrations.AddField(
            model_name='signupdata',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
