# Generated by Django 2.2.3 on 2024-02-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_auto_20240225_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdata',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
