# Generated by Django 2.2.3 on 2024-02-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20240225_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('bucketid', models.IntegerField()),
                ('data', models.TextField()),
            ],
        ),
    ]
